fpabi:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "ctqlryr-ea47137"
      user: "DBT_USER2"
      password: "W8!kR2#pL9@xS4nD1hQ7"
      role: "FPABI_DBT_ROLE"
      warehouse: "FPABI_WH"
      database: "FPABI"
      schema: "DBT"
      threads: 8
