# Save as ~/.dbt/profiles.yml
# Admin password is NOT used by dbt. Only DBT_USER credentials are used below.
fpabi:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "ctqlryr-ea47137"
      user: "DBT_USER"
      password: "lKx^4j^B#P&fYs!aQ(%Y"
      role: "FPABI_DBT_ROLE"
      warehouse: "FPABI_WH"
      database: "FPABI"
      schema: "DBT"
      threads: 8
      client_session_keep_alive: false
