fpabi:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "ctqlryr-ea47137"
      user: "DBT_USER"
      password: "R9m!q2Vt#7KpX4sNw@1F"
      role: "FPABI_DBT_ROLE"
      warehouse: "FPABI_WH"
      database: "FPABI"
      schema: "DBT"
      threads: 8
