fpabi:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "past_your_snowflake_id_here" 
      user: "past_your_snowflake_user_here"
      password: "past_your_snowflake_user_password_here"
      role: "FPABI_DBT_ROLE"
      warehouse: "FPABI_WH"
      database: "FPABI"
      schema: "DBT"
      threads: 8
